### PR TITLE
build: Improve tooling

### PR DESCRIPTION
**Pull request by stdtom**
This PR contains several improvements to the build tooling:

1. Add flake8 as linter
1. Add pre-commit and hooks for black and flake8
1. Add tox for local multi environment testing
1. Add Makefile for build automation

### Flake8 as linter
Flake8 detects several code issues which are not detected by black, such as:

* undefined names
* unused variables
* unused imports
* invalid escape sequence

Initial flake8 run on master reported the following issues which have been resolved as part of this PR:
```
$ poetry run flake8 auto_changelog tests
auto_changelog/domain_model.py:9:54: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:58: W605 invalid escape sequence '\.'
auto_changelog/domain_model.py:9:77: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:81: W605 invalid escape sequence '\.'
auto_changelog/domain_model.py:9:100: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:121: E501 line too long (274 > 120 characters)
auto_changelog/domain_model.py:9:134: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:138: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:167: W605 invalid escape sequence '\.'
auto_changelog/domain_model.py:9:179: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:183: W605 invalid escape sequence '\d'
auto_changelog/domain_model.py:9:217: W605 invalid escape sequence '\+'
auto_changelog/domain_model.py:9:253: W605 invalid escape sequence '\.'
tests/test_repository.py:109:121: E501 line too long (163 > 120 characters)
tests/test_repository.py:129:121: E501 line too long (124 > 120 characters)
tests/test_presenter.py:5:1: F401 'auto_changelog.domain_model.default_tag_pattern' imported but unused
tests/test_presenter.py:46:121: E501 line too long (126 > 120 characters)
```

### pre-commit
Adds hooks for black and flake8 to ensure that changes are linted and blackened before committing.

### tox 
Supports checking the package against multiple supported Python versions on th local development machine.

### CODE REVIEW

**Comment by KeNaCo** [comment]
Can you, please, split it into 4 PRs, so I can comment and merge them independently?

**Comment by stdtom** [comment]
> Can you, please, split it into 4 PRs, so I can comment and merge them independently?

Sure I can. I just want to point out that there are some dependencies:
grafik

E.g. e06b325 and  f6f704a will only make sense if ea1fdc7 and 7928448 have been merged before.

That's also the reason why this PR also contains commits submitted with #91.

**Comment by stdtom** [comment]
> Can you, please, split it into 4 PRs, so I can comment and merge them independently?

I split PR #92 into several pull request, so you can comment on them incrementally.
Nevertheless due to the dependencies they are still cummulative and thus hould be applied in the folloing order:
#91 > #95 > #96 > #97 > #92 

If you don't like some of the features (e.g. flake8 or tox) - although it would be a pitty ;-)  - let me know and I will rebase and modify the subsequent once to fit.

**Comment by stdtom** [comment]
Just updated  Contributing" section in README to cover usage of make and pre-commit

**Comment by KeNaCo** [comment]
According to comments, this should be the last one merged, containing Makefile. Correct?

**Comment by stdtom** [comment]
Yes, indeed. And now it has been rebased as well. 😃

**Pull request merged**
