### PR TITLE
build: Add tox

### PR DESCRIPTION
**Pull request by stdtom**
Adding tox to build tooling.
Tox supports checking the package against multiple supported Python versions on th local development machine.

### CODE REVIEW

**Comment by stdtom** [comment]
I split PR #92 into several pull request, so you can comment on them incrementally.
Nevertheless due to the dependencies they are still cummulative and thus hould be applied in the folloing order:
#91 > #95 > #96 > #97 > #92 

If you don't like some of the features (e.g. flake8 or tox) - although it would be a pitty ;-)  - let me know and I will rebase and modify the subsequent once to fit.

**Comment by KeNaCo** [comment]
I see this PR contains also pre-commit and black configuration, but no conflicts.. can I merge it?

**Comment by stdtom** [comment]
Yes, I just rebased it.

**Comment by KeNaCo** [comment]
Merging then.

**Pull request merged**
